feat(nextcloud): add push notifications

diff --git a/clusters/corpus/apps/personal/nextcloud/helmrelease.yaml b/clusters/corpus/apps/personal/nextcloud/helmrelease.yaml
--- a/clusters/corpus/apps/personal/nextcloud/helmrelease.yaml
+++ b/clusters/corpus/apps/personal/nextcloud/helmrelease.yaml
@@ -131,7 +131,13 @@ spec:
                 red="\e[1;31m"
                 for op in "$${ops[@]}" ; do
                   echo -e "$${grey}Running php occ $op $reset"
-                  su www-data -s /usr/local/bin/php -- occ $op && echo -en "$green" || echo -en "$red"
+                  while :;
+                    su www-data -s /usr/local/bin/php -- occ $op && echo -en "$green" || echo -en "$red"
+                    if [[] $? != 0 ]]; then
+                      echo -e "$${grey}Command failed, retrying..."
+                      sleep 1
+                      continue
+                    fi
                   echo -e "Finished php occ $op $reset"
                 done &&
                 su www-data \
